# Generated by Django 2.2.4 on 2019-08-31 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team_projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField(auto_now_add=True, verbose_name='Time In')),
                ('hours', models.PositiveIntegerField(verbose_name='Number of Hours')),
                ('task_description', models.TextField(verbose_name='Task Description')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_time_entries', to='team_projects.Project', verbose_name='Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_time_entries', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Time Entry',
                'verbose_name_plural': 'Time Entries',
            },
        ),
    ]
